export const actionType = {
    // CREATE_USER: 'CREATE_USER'

    // LATEST_PRICE
    GET_PRICE : 'GET_PRICE',

    // USER
    USER_LOGIN : 'USER_LOGIN',
    USER_LOGOUT : 'USER_LOGOUT',

    // WALLET
    CREATE_WALLET : 'CREATE_WALLET',
    GET_WALLET : 'GET_WALLET',
    UPDATE_WALLET : 'UPDATE_WALLET',
    CREATE_DB_WALLET : 'CREATE_DB_WALLET',
    GET_DB_WALLET : 'GET_DB_WALLET',
    UPDATE_DB_WALLET : 'UPDATE_DB_WALLET',
    

    // TRADE_HISTORY
    GET_TRADE_HISTORY : 'GET_TRADE_HISTORY',
    ADD_TRADE_HISTORY : 'ADD_TRADE_HISTORY',
    GET_DB_TRADE_HISTORY : 'GET_DB_TRADE_HISTORY',
    ADD_DB_TRADE_HISTORY : 'ADD_DB_TRADE_HISTORY',

    // COMMENT
    ADD_COMMENTS : 'ADD_COMMENTS',
    GET_ALL_COMMENTS : 'GET_ALL_COMMENTS',
    GET_USER_COMMENTS : 'GET_USER_COMMENTS',
    ADD_DB_COMMENTS : 'ADD_DB_COMMENTS',
    GET_DB_ALL_COMMENTS : 'GET_DB_ALL_COMMENTS',
    GET_DB_USER_COMMENTS : 'GET_DB_USER_COMMENTS',

    // ERROR
    EMIT_ERROR : 'EMIT_ERROR'
}